model('form-select',function(){
    //下拉框
    this.$model = {
        selectChange:function () {
            console.log(this.value)
        },
        selectData:{
            style:{
                //样式可自定义
                width:'100%',

            },
            config:{
                //配置参数key 固定
                name:'selectList',
                class:'selecttttt',
                multiple:false,
            },

            dataList:[
                {
                    isGroup:true,
                    label:'水果',
                    list:[
                        {
                            isGroup:false,
                            disabled:true,//是否不可以选择,默认false(即可选择)
                            content:'西瓜3213135112FFFFFFFFFFFFFFFFFFFFF32131',
                            value:'水果1',
                            selected:true
                        },
                        {
                            isGroup:false,
                            disabled:true,
                            content:'橙子',
                            value:'水果2',
                            selected:true
                        },
                        {
                            isGroup:false,
                            disabled:false,
                            content:'苹果',
                            value:'水果3',
                            selected:true
                        },
                        {
                            isGroup:false,
                            disabled:false,
                            content:'山竹',
                            value:'水果4',
                            selected:true
                        },
                    ]
                },
                {
                    isGroup:true,
                    content:'衣服',
                    value:'衣服',
                    selected:true
                },
                {
                    isGroup:true,
                    content:'饮料',
                    value:'饮料',
                    selected:true
                },
                {
                    isGroup:true,
                    content:'办公用品',
                    list:[
                        {
                            isGroup:false,
                            disabled:false,
                            content:'铅笔',
                            value:'办公用品1',
                            selected:true
                        },
                        {
                            isGroup:false,
                            disabled:false,
                            content:'橡皮',
                            value:'办公用品2',
                            selected:true
                        },
                        {
                            isGroup:false,
                            disabled:false,
                            content:'钢笔',
                            value:'办公用品3',
                            selected:true
                        },
                        {
                            isGroup:false,
                            disabled:false,
                            content:'尺子',
                            value:'办公用品4'
                        }
                    ]
                }

            ]
        }
    };


});

//图标选择
model('icons-select',function(){
    this.$model = {
        iconConfig:{
            cols:4,//不填默认一行显示4个图标
        },
        icons:[
            "icon-yonghuming",
            "icon-mima",
            "icon-qiandao",
            "icon-dingdan",

            "icon-qiandao",
            "icon-qianyue",
            "icon-wenjianjia",
            "icon-icon4",

            "icon-fanhui",
            "icon-baoji",
            "icon-xiaoshou",
            "icon-hot",

            "icon-jinggaofull",
            "icon-baocun",
            "icon-sousuoleibie",
            "icon-chanpin"
        ],
        events:{
            click:function(){
                console.log(this.title,'icon-title')
            }
        }
    }
})
